spring:
  application:
    name: test_maven
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true